### ISSUE TITLE
Error with some events without service

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-module-logs#14]
Noticed in the logs:
```
[2017-04-05 06:19:14 CEST] ERROR: [alignak.module.logs] Exception: Backend error code 422: Insertion failure: 1 document(s) contain(s) error(s)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak_module_logs/logs.py", line 316, in manage_brok
    self.backend.post('history', data)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 549, in post
    raise BackendException(error['code'], error['message'], resp)
BackendException: Backend error code 422: Insertion failure: 1 document(s) contain(s) error(s)
[2017-04-05 06:19:14 CEST] ERROR: [alignak.module.logs] Exception response: {u'_status': u'ERR', u'_issues': {u'service_name': [u'null value not allowed', u'must be of string type']}, u'_error': {u'message': u'Insertion failure: 1 document(s) contain(s) error(s)', u'code': 422}}

```

**Comment by mohierf** [comment]
More information:
```
[2017-04-05 08:00:00 CEST] INFO: [alignak.module.logs] Got monitoring log brok: {'uuid': u'3b3afbe618bc44a0bd6db4121f4bf1c4', 'data': {'instance_id': u'1bd1f1d29afe4147b6c78
0421ef27612', u'message': u'HOST NOTIFICATION: northman;passive-01;UP;notify-host-by-email;WS output - active checks disabled', u'level': u'info'}, 'creation_time': 14913720
00.048431, 'prepared': True, 'instance_id': u'1bd1f1d29afe4147b6c780421ef27612', 'type': u'monitoring_log'}

[2017-04-05 08:00:00 CEST] ERROR: [alignak.module.logs] Exception: Backend error code 422: Insertion failure: 1 document(s) contain(s) error(s)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak_module_logs/logs.py", line 317, in manage_brok
    self.backend.post('history', data)
  File "/usr/local/lib/python2.7/site-packages/alignak_backend_client/client.py", line 549, in post
    raise BackendException(error['code'], error['message'], resp)
BackendException: Backend error code 422: Insertion failure: 1 document(s) contain(s) error(s)

```

The problem seems to be raised for an host notification
