### ISSUE TITLE
Unable to configure handler 'rotating_file_handler'

### ISSUE THREAD

**Issue by spea1** [Alignak-monitoring-contrib/alignak-module-logs#21]
**alignak-module-backend:**
Date:   Fri Jun 23 19:57:10 2017 +0200
caab6dbff63be16adaa13af0b5a2322b0d4eccd4
Branch: retention-load-message

**alignak-module-logs:**
Date:   Thu Jun 22 08:54:10 2017 +0200
24439ec622d325fbd0eb2205c099b5a1aa23628c
Branch: develop+more-events
````
[2017-06-24 12:07:01 CEST] INFO: [alignak.daemons.brokerdaemon] We have our receivers:
[2017-06-24 12:07:01 CEST] INFO: [alignak.daemons.brokerdaemon]  - receiver-master
[2017-06-24 12:07:01 CEST] INFO: [alignak.daemons.brokerdaemon]  - receiver-slave
[2017-06-24 12:07:01 CEST] INFO: [alignak.daemon] Loading modules...
[2017-06-24 12:07:01 CEST] INFO: [alignak.modulesmanager] Importing Python module 'alignak_module_backend.broker' for backend_broker...
[2017-06-24 12:07:01 CEST] INFO: [alignak.modulesmanager] Module properties: {'daemons': ['broker'], 'type': 'backend_broker', 'external': True}
[2017-06-24 12:07:01 CEST] INFO: [alignak.modulesmanager] Imported 'alignak_module_backend.broker' for backend_broker
[2017-06-24 12:07:01 CEST] INFO: [alignak.modulesmanager] Loaded Python module 'alignak_module_backend.broker' (backend_broker)
[2017-06-24 12:07:01 CEST] INFO: [alignak.modulesmanager] Importing Python module 'alignak_module_logs' for logs...
[2017-06-24 12:07:01 CEST] INFO: [alignak.modulesmanager] Module properties: {'daemons': ['broker'], 'phases': ['running'], 'type': 'logs','external': True}
[2017-06-24 12:07:01 CEST] INFO: [alignak.modulesmanager] Imported 'alignak_module_logs' for logs
[2017-06-24 12:07:01 CEST] INFO: [alignak.modulesmanager] Loaded Python module 'alignak_module_logs' (logs)
[2017-06-24 12:07:01 CEST] INFO: [alignak.module.backend_broker] Give an instance of alignak_module_backend.broker for alias: backend_broker
[2017-06-24 12:07:01 CEST] INFO: [alignak.module.backend_broker] Number of processes used by backend client: 1
[2017-06-24 12:07:01 CEST] INFO: [alignak.module.logs] Give an instance of alignak_module_logs for alias: logs
[2017-06-24 12:07:01 CEST] INFO: [alignak.module.logs] logger configuration defined in /usr/local/etc/alignak/arbiter/modules/mod-logs-logger.json
[2017-06-24 12:07:01 CEST] ERROR: [alignak.module.logs] Logger configuration file is not parsable correctly!
[2017-06-24 12:07:01 CEST] ERROR: [alignak.module.logs] Unable to configure handler u'rotating_file_handler': __init__() got an unexpected keyword argument 'when'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak_module_logs/logs.py", line 195, in setup_logging
    logger_dictConfig(config)
  File "/usr/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 576, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure handler u'rotating_file_handler': __init__() got an unexpected keyword argument 'when'
[2017-06-24 12:07:01 CEST] INFO: [alignak.module.logs] Alignak backend endpoint: http://backend.mydom.local:5000
[2017-06-24 12:07:01 CEST] INFO: [alignak.module.logs] Number of processes used by backend client: 1
[2017-06-24 12:07:01 CEST] INFO: [alignak.module.logs] Signing-in to the backend...
[2017-06-24 12:07:01 CEST] INFO: [alignak.daemon] I correctly loaded my modules: [backend_broker,logs]
[2017-06-24 12:07:01 CEST] INFO: [alignak.modulesmanager] Trying to initialize module: backend_broker
[2017-06-24 12:07:01 CEST] INFO: [alignak.modulesmanager] Starting external module backend_broker
[2017-06-24 12:07:01 CEST] INFO: [alignak.basemodule] Starting external process for module backend_broker...
[2017-06-24 12:07:01 CEST] INFO: [alignak.basemodule] backend_broker is now started (pid=11780)
[2017-06-24 12:07:01 CEST] INFO: [alignak.modulesmanager] Trying to initialize module: logs
[2017-06-24 12:07:02 CEST] INFO: [alignak.basemodule] Process for module backend_broker is now running (pid=11780)
[2017-06-24 12:07:02 CEST] INFO: [alignak.module.backend_broker] starting...
[2017-06-24 12:07:02 CEST] INFO: [alignak.modulesmanager] Starting external module logs
[2017-06-24 12:07:02 CEST] INFO: [alignak.basemodule] Starting external process for module logs...
[2017-06-24 12:07:02 CEST] INFO: [alignak.basemodule] logs is now started (pid=11790)
[2017-06-24 12:07:02 CEST] INFO: [alignak.daemons.brokerdaemon] Setting our timezone to Europe/Paris
ValueError: Unable to configure handler u'rotating_file_handler': __init__() got an unexpected keyword argument 'when'
[2017-06-24 12:07:01 CEST] INFO: [alignak.module.logs] Alignak backend endpoint: http://backend.mydom.local:5000
[2017-06-24 12:07:01 CEST] INFO: [alignak.module.logs] Number of processes used by backend client: 1
[2017-06-24 12:07:01 CEST] INFO: [alignak.module.logs] Signing-in to the backend...
[2017-06-24 12:07:01 CEST] INFO: [alignak.daemon] I correctly loaded my modules: [backend_broker,logs]
[2017-06-24 12:07:01 CEST] INFO: [alignak.modulesmanager] Trying to initialize module: backend_broker
[2017-06-24 12:07:01 CEST] INFO: [alignak.modulesmanager] Starting external module backend_broker
[2017-06-24 12:07:01 CEST] INFO: [alignak.basemodule] Starting external process for module backend_broker...
[2017-06-24 12:07:01 CEST] INFO: [alignak.basemodule] backend_broker is now started (pid=11780)
[2017-06-24 12:07:01 CEST] INFO: [alignak.modulesmanager] Trying to initialize module: logs
[2017-06-24 12:07:02 CEST] INFO: [alignak.basemodule] Process for module backend_broker is now running (pid=11780)
[2017-06-24 12:07:02 CEST] INFO: [alignak.module.backend_broker] starting...
[2017-06-24 12:07:02 CEST] INFO: [alignak.modulesmanager] Starting external module logs
[2017-06-24 12:07:02 CEST] INFO: [alignak.basemodule] Starting external process for module logs...
[2017-06-24 12:07:02 CEST] INFO: [alignak.basemodule] logs is now started (pid=11790)
[2017-06-24 12:07:02 CEST] INFO: [alignak.daemons.brokerdaemon] Setting our timezone to Europe/Paris
[2017-06-24 12:07:02 CEST] INFO: [alignak.daemons.brokerdaemon] Connection OK to the scheduler scheduler-master
[2017-06-24 12:07:02 CEST] INFO: [alignak.basemodule] Process for module logs is now running (pid=11790)
[2017-06-24 12:07:02 CEST] INFO: [alignak.module.logs] starting...
[2017-06-24 12:07:02 CEST] INFO: [alignak.daemons.brokerdaemon] Connection OK to the poller poller-master
[2017-06-24 12:07:02 CEST] INFO: [alignak.daemons.brokerdaemon] Connection OK to the reactionner reactionner-slave
[2017-06-24 12:07:02 CEST] INFO: [alignak.daemons.brokerdaemon] Connection OK to the reactionner reactionner-master
[2017-06-24 12:07:02 CEST] INFO: [alignak.daemons.brokerdaemon] Connection OK to the receiver receiver-master
[2017-06-24 12:07:02 CEST] INFO: [alignak.daemons.brokerdaemon] Connection OK to the receiver receiver-slave
[2017-06-24 12:07:11 CEST] INFO: [alignak.module.backend_broker] Got configuration
[2017-06-24 12:07:11 CEST] INFO: [alignak.module.backend_broker] Hosts/services references reloaded
[2017-06-24 12:09:45 CEST] WARNING: [alignak.module.logs] No monitoring event detected from: SERVICE EVENT HANDLER: localhost;Load;CRITICAL;HARD;3;g_servi$
[2017-06-24 12:09:49 CEST] INFO: [alignak.module.backend_broker] service / Load, some modifications exist: {u'freshness_threshold': 3600, u'initial_state'$
[2017-06-24 12:09:49 CEST] INFO: [alignak.module.backend_broker] Updated service: localhost__Load.

````

````
# -----------------------------------------------------------------------------
# /usr/local/etc/alignak/arbiter/modules/mod-logs-logger.json
# -----------------------------------------------------------------------------

{
    "version": 1,
    "disable_existing_loggers": false,
    "formatters": {
        "local": {
            "format": "[%(asctime)s] %(levelname)s: [%(name)s] %(message)s"
        }
    },

    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "level": "DEBUG",
            "formatter": "local",
            "stream": "ext://sys.stdout"
        },
        "rotating_file_handler": {
            "class": "logging.handlers.RotatingFileHandler",
            "level": "INFO",
            "formatter": "local",
            "filename": "/usr/local/var/log/alignak/rotating-monitoring.log",
            "when": "midnight",
            "interval": 1,
            "backupCount": 7,
            "encoding": "utf8"
        },
        "timed_rotating_file_handler": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "level": "INFO",
            "formatter": "local",
            "filename": "/usr/local/var/log/alignak/timed-rotating-monitoring.log",
            "when": "midnight",
            "interval": 1,
            "backupCount": 7,
            "encoding": "utf8"
        },
        "monitoring_logs": {
            "class": "logging.handlers.TimedRotatingFileHandler",
            "level": "INFO",
            "formatter": "local",
            "filename": "/usr/local/var/log/alignak/monitoring-logs.log",
            "when": "midnight",
            "interval": 1,
            "backupCount": 30,
            "encoding": "utf8"
        }
    },

    "loggers": {
        "monitoring-logs": {
            "level": "INFO",
            "handlers": ["monitoring_logs"],
            "propagate": "no"
        }
    },

    "root": {
        "level": "INFO",
        "handlers": ["console", "timed_rotating_file_handler"]
    }
}

````

**Comment by mohierf** [comment]
Fixed with 1.2.0
