### ISSUE TITLE
Exception on an external command parsing

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-module-logs#22]
See:
```
[2017-07-30 11:53:59 CEST] INFO: [alignak.module.web-services] Authenticated with backend
[2017-07-30 11:53:59 CEST] INFO: [alignak.module.web-services] Got an external command: [1501408431] PROCESS_HOST_CHECK_RESULT;vm-fafafdj-0004;0;;;

==> /usr/local/var/log/alignak/monitoring-logs.log <==
[1501408440] INFO: HOST ALERT: vm-fafafdj-0004;UP;HARD;0;;;

==> /usr/local/var/log/alignak/brokerd.log <==
[2017-07-30 11:54:00 CEST] ERROR: [alignak.basemodule] [logs] main function exception: invalid literal for int() with base 10: ''
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/basemodule.py", line 418, in _main
    self.main()
  File "/usr/local/lib/python2.7/site-packages/alignak_module_logs/logs.py", line 354, in main
    self.manage_brok(brok)
  File "/usr/local/lib/python2.7/site-packages/alignak_module_logs/logs.py", line 257, in manage_brok
    event = LogEvent(('[%s] ' % int(time.time())) + brok.data['message'])
  File "/usr/local/lib/python2.7/site-packages/alignak_module_logs/logevent.py", line 249, in __init__
    self.data['attempts'] = int(self.data['attempts'])
ValueError: invalid literal for int() with base 10: ''

```

**Comment by mohierf** [comment]
Still another example:
```
[2017-09-21 17:02:13 CEST] ERROR: [alignak.basemodule] [logs] main function exception: invalid literal for int() with base 10: 'Check output from WebUI'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/alignak/basemodule.py", line 418, in _main
    self.main()
  File "/usr/local/lib/python2.7/site-packages/alignak_module_logs/logs.py", line 353, in main
    self.manage_brok(brok)
  File "/usr/local/lib/python2.7/site-packages/alignak_module_logs/logs.py", line 257, in manage_brok
    event = LogEvent(('[%s] ' % int(time.time())) + brok.data['message'])
  File "/usr/local/lib/python2.7/site-packages/alignak_module_logs/logevent.py", line 307, in __init__
    self.data['attempts'] = int(self.data['attempts'])
ValueError: invalid literal for int() with base 10: 'Check output from WebUI'
[2017-09-21 17:02:13 CEST] INFO: [alignak.basemodule] Process for module logs is now exiting (pid=70923)
[2017-09-21 17:02:14 CEST] ERROR: [alignak.modulesmanager] The external module logs died unexpectedly!
[2017-09-21 17:02:14 CEST] INFO: [alignak.modulesmanager] Setting the module logs to restart
[2017-09-21 17:02:14 CEST] INFO: [alignak.modulesmanager] Trying to initialize module: logs
[2017-09-21 17:02:15 CEST] INFO: [alignak.basemodule] I'm stopping module u'logs' (pid=70923)
[2017-09-21 17:02:15 CEST] INFO: [alignak.basemodule] Starting external process for module logs...
[2017-09-21 17:02:15 CEST] INFO: [alignak.basemodule] logs is now started (pid=70964)
[2017-09-21 17:02:15 CEST] INFO: [alignak.basemodule] Process for module logs is now running (pid=70964)
[2017-09-21 17:02:15 CEST] INFO: [alignak.module.logs] starting...

```

**Comment by mohierf** [comment]
The same problem exist for any log that has a semi-colon after the output 😞 

all the parsing regex stuff should be rewritten properly !

**Comment by mohierf** [comment]
Currently protect with catching the exception and raising a WARNING log. The event is stored in the monitoring log file but will not be stored to the backend....
