### ISSUE TITLE
Error in the brokerd - console handler

### ISSUE THREAD

**Issue by mohierf** [Alignak-monitoring-contrib/alignak-module-logs#6]
As reported by @spea1:

```
[2016-12-20 20:11:27 UTC] INFO: [alignak.module] Give an instance of alignak_module_logs for alias: logs
[2016-12-20 20:11:27 UTC] INFO: [alignak.module.logs] logger configuration defined in /usr/local/etc/alignak/arbiter/module
s/mod-logs-logger.json
[2016-12-20 20:11:27 UTC] ERROR: [alignak.module.logs] Logger configuration file is not parsable correctly!
[2016-12-20 20:11:27 UTC] ERROR: [alignak.module.logs] Unable to configure logger 'alignak.module.logs': Unable to add handler u'console': u'console'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/alignak_module_logs-0.2.3-py2.7.egg/alignak_module_logs/logs.py", line 152,in setup_logging
    logger_dictConfig(config)
  File "/usr/lib/python2.7/logging/config.py", line 794, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python2.7/logging/config.py", line 627, in configure
    '%r: %s' % (name, e))
ValueError: Unable to configure logger 'alignak.module.logs': Unable to add handler u'console': u'console'

```

**Comment by mohierf** [comment]
Sould be fixed with the most recent version
